# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20180607_2027'),
        ('patientlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='orgs.Org'),
        ),
    ]
