# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0002_log_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
