# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0004_log_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='patientlog.Log'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='logger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='patientlog.Tag'),
        ),
    ]
