# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20180607_2027'),
        ('patientlog', '0005_auto_20180607_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_org', to='orgs.Org')),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_org', to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_org', to='orgs.Org'),
        ),
    ]
