# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0007_auto_20180608_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
