# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0008_entry_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='participants',
        ),
        migrations.AddField(
            model_name='entry',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='participants', to='patientlog.Resident'),
        ),
    ]
