# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0010_auto_20180608_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='residents',
            field=models.ManyToManyField(related_name='residents', to='patientlog.Resident'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='patientlog.Tag'),
        ),
    ]
