# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0012_auto_20180618_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='room',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='time_admitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
