# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 01:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0013_auto_20180618_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='time_admitted',
            new_name='timestamp_admitted',
        ),
        migrations.AddField(
            model_name='resident',
            name='timestamp_left',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
