# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientlog', '0016_resident_advocates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='importance',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='should_email',
            field=models.BooleanField(default=False),
        ),
    ]
