# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0003_auto_20180607_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='members',
        ),
        migrations.AddField(
            model_name='org',
            name='members',
            field=models.ManyToManyField(null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
