# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-18 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20180613_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='org',
            name='unapproved',
            field=models.ManyToManyField(blank=True, related_name='unapproved', to=settings.AUTH_USER_MODEL),
        ),
    ]
