# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orgs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(blank=True, default='EST', max_length=50),
        ),
    ]
